export const courses = [
  {
    id: 1,
    category: 'marketing',
    title: 'The Ultimate Google Ads Training Course',
    price: 100,
    author: 'Jerome Bell',
  },
  {
    id: 2,
    category: 'management',
    title: 'Prduct Management Fundamentals',
    price: 480,
    author: 'Marvin McKinney',
  },
  {
    id: 3,
    category: 'hr',
    title: 'HR Management and Analytics',
    price: 200,
    author: 'Leslie Alexander Li',
  },
  {
    id: 4,
    category: 'marketing',
    title: 'Brand Management & PR Communications',
    price: 530,
    author: 'Kristin Watson',
  },
  {
    id: 5,
    category: 'design',
    title: 'Graphic Design Basic',
    price: 500,
    author: 'Guy Hawkins',
  },
  {
    id: 6,
    category: 'management',
    title: 'Business Development Management',
    price: 400,
    author: 'Dianne Russell',
  },
  {
    id: 7,
    category: 'development',
    title: 'Highload Software Architecture',
    price: 600,
    author: 'Brooklyn Simmons',
  },
  {
    id: 8,
    category: 'hr',
    title: 'Human Resources - Selection and Recruitment',
    price: 150,
    author: 'Kathryn Murphy',
  },
  {
    id: 9,
    category: 'design',
    title: 'User Experience. Human-centered Design',
    price: 240,
    author: 'Cody Fisher',
  },
  {
    id: 1,
    category: 'marketing',
    title: 'The Ultimate Google Ads Training Course',
    price: 100,
    author: 'Jerome Bell',
  },
  {
    id: 2,
    category: 'management',
    title: 'Prduct Management Fundamentals',
    price: 480,
    author: 'Marvin McKinney',
  },
  {
    id: 3,
    category: 'hr',
    title: 'HR Management and Analytics',
    price: 200,
    author: 'Leslie Alexander Li',
  },
  {
    id: 4,
    category: 'marketing',
    title: 'Brand Management & PR Communications',
    price: 530,
    author: 'Kristin Watson',
  },
  {
    id: 5,
    category: 'design',
    title: 'Graphic Design Basic',
    price: 500,
    author: 'Guy Hawkins',
  },
  {
    id: 6,
    category: 'management',
    title: 'Business Development Management',
    price: 400,
    author: 'Dianne Russell',
  },
  {
    id: 7,
    category: 'development',
    title: 'Highload Software Architecture',
    price: 600,
    author: 'Brooklyn Simmons',
  },
  {
    id: 8,
    category: 'hr',
    title: 'Human Resources - Selection and Recruitment',
    price: 150,
    author: 'Kathryn Murphy',
  },
  {
    id: 9,
    category: 'design',
    title: 'User Experience. Human-centered Design',
    price: 240,
    author: 'Cody Fisher',
  },
];

export const CATEGORY_LABELS = {
  all: 'All',
  marketing: 'Marketing',
  management: 'Management',
  hr: 'HR & Recruiting',
  design: 'Design',
  development: 'Development',
};
